name: Build and Deploy My Jekyll Site


on:
  push:
    branches: 
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Specify the Ruby version you need
      - name: Install dependencies
        run: |
          gem install bundler --user-install
          bundle install
      - name: Build Jekyll Site
        run: nbundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site